### ISSUE TITLE
能否添加对 GitHub alert 语法的支持以及调整代码高亮的配色？

### ISSUE THREAD

**Issue by immadolf** [sivan/devonthink-heti#16]
你好，目前没有针对 [alert](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) 的支持，显示效果如下
<img width="914" alt="image" src="https://github.com/sivan/devonthink-heti/assets/12369197/73709f18-e12c-4c28-8837-7ec9a92511cc">

还有就是默认的代码样式太素了，能做一些调整吗？
<img width="458" alt="image" src="https://github.com/sivan/devonthink-heti/assets/12369197/4c700a05-a820-4ddc-8b85-ea1c2be038ad">

**Comment by sivan** [comment]
这个css补丁只能针对DEVONthink渲染完的样式做一下优化，一些特殊语法如果本身没解析的话就没法优化样式了。

代码高亮的功能，可以在DEVONthink的设置-「Files」-「Markdown」里开启「Prism support」就可以了~

**Comment by immadolf** [comment]
好的，感谢您的回复。
我补充一下，开启 「Prism support」后，代码块要用
<img width="384" alt="image" src="https://github.com/sivan/devonthink-heti/assets/12369197/35803073-5fa4-4dd0-a5e2-6a8f38da07ad">
才能开启高亮。
