### ISSUE TITLE
DT3.62开始支持criticmarkup语法了

### ISSUE THREAD

**Issue by bosconb** [sivan/devonthink-heti#4]
我试了下注释{>> <<}，好像不起作用，我不确定是devonthink的原因，如果是可以更新优化下吗? 谢过大佬！

**Comment by sivan** [comment]
> 我试了下注释{>> <<}，好像不起作用，我不确定是devonthink的原因，如果是可以更新优化下吗? 谢过大佬！

这种标记的注释没有特殊标签，是通过 class 实现的，晚些我加一个上去。

**Comment by bosconb** [comment]
> > 我试了下注释{>> <<}，好像不起作用，我不确定是devonthink的原因，如果是可以更新优化下吗? 谢过大佬！
> 
> 这种标记的注释没有特殊标签，是通过 class 实现的，晚些我加一个上去。

谢谢！！期待

**Comment by sivan** [comment]
已在 https://github.com/sivan/devonthink-heti/commit/133e0819d394cb7cc923403324aec7b003e65801 增加样式 :-)
